const MIN_PLAYERS_BY_GAME_CODE: Record<string, number> = {
  barnbarter: 1,
  bashni: 2,
  bingo: 2,
  bombsAndBunnies: 2,
  bridge: 4,
  bullsAndCows: 2,
  cardtable: 2,
  checkers: 2,
  chess: 2,
  cornerus: 2,
  doppelkopf: 4,
  estatebuyer: 2,
  fourinarow: 2,
  frenchTarot: 3,
  hangman: 2,
  kriegspiel: 2,
  mancala: 2,
  memorymatch: 2,
  mergers: 3,
  ninemensmorris: 2,
  picnicGo: 2,
  picnicGoTest: 2,
  reversi: 2,
  rota: 2,
  schafkopf: 3,
  seabattle: 2,
  secretDracula: 5,
  secretcodes: 4,
  sixtysix: 2,
  skat: 3,
  soupofletters: 2,
  takesix: 2,
  tictactoe: 2,
  tictactoeplus: 2,
  war: 2,
  zooparade: 2,
  zwanzigerrufen: 4,
};

export function getMinPlayersForGame(
  gameCode: string,
  fallback: number,
): number {
  return MIN_PLAYERS_BY_GAME_CODE[gameCode] ?? fallback;
}
